Repository AY2425S1-CS2103T-F13-3/tp, pull requests merged in 2024-10, with the labels that each got.

#118 Revamp UI
  copyright.txt
  src/main/java/seedu/ddd/ui/ClientCard.java
  src/main/java/seedu/ddd/ui/ContactListPanel.java
  src/main/java/seedu/ddd/ui/MainWindow.java
  src/main/java/seedu/ddd/ui/Sidebar.java
  src/main/java/seedu/ddd/ui/VendorCard.java
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/fail.png
  src/main/resources/images/help_icon.png
  src/main/resources/images/info_icon.png
  src/main/resources/images/logo.png
  src/main/resources/images/title.png
  src/main/resources/view/ClientCard.fxml
  src/main/resources/view/CommandBox.css
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ContactCard.css
  src/main/resources/view/ContactListPanel.css
  src/main/resources/view/ContactListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.css
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/Sidebar.css
  src/main/resources/view/Sidebar.fxml
  src/main/resources/view/VendorCard.fxml
Labels: Enhancement

#119 Create Event and corresponding test class
  src/main/java/seedu/ddd/model/AddressBook.java
  src/main/java/seedu/ddd/model/Model.java
  src/main/java/seedu/ddd/model/ModelManager.java
  src/main/java/seedu/ddd/model/ReadOnlyAddressBook.java
  src/main/java/seedu/ddd/model/event/Description.java
  src/main/java/seedu/ddd/model/event/Event.java
  src/main/java/seedu/ddd/model/event/EventId.java
  src/main/java/seedu/ddd/model/event/UniqueEventList.java
  src/main/java/seedu/ddd/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/ddd/model/event/exceptions/EventNotFoundException.java
  src/test/java/seedu/ddd/logic/commands/AddCommandTest.java
  src/test/java/seedu/ddd/model/AddressBookTest.java
  src/test/java/seedu/ddd/model/event/DescriptionTest.java
  src/test/java/seedu/ddd/model/event/EventTest.java
Labels: Feature

#135 Fix stub
  src/test/java/seedu/ddd/logic/commands/AddEventCommandTest.java
Labels: Bug

#142 Fix displayed list desync
  src/main/java/seedu/ddd/logic/commands/ListCommand.java
  src/main/java/seedu/ddd/model/ModelManager.java
Labels: Bug

#139 Update DG
  README.md
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/johndoe.png
  docs/images/view-tag-example.png
  docs/index.md
Labels: Documentation

#145 Update UG
  docs/UserGuide.md
  src/main/java/seedu/ddd/logic/Messages.java
  src/main/java/seedu/ddd/logic/commands/AddCommand.java
  src/main/java/seedu/ddd/logic/commands/AddEventCommand.java
  src/main/java/seedu/ddd/logic/commands/DeleteCommand.java
  src/main/java/seedu/ddd/logic/commands/EditCommand.java
  src/main/java/seedu/ddd/logic/commands/HelpCommand.java
  src/main/java/seedu/ddd/logic/commands/ListCommand.java
  src/main/java/seedu/ddd/logic/commands/ListEventCommand.java
  src/main/java/seedu/ddd/logic/parser/AddCommandParser.java
  src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
  src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
Labels: Documentation

#168 Fix compile error
  src/main/java/seedu/ddd/model/util/SampleDataUtil.java
Labels: Bug
