Repository AY2425S1-CS2103T-F13-3/tp, pull requests merged in 2024-11, with the labels that each got.

#165 Fix listing
  src/main/java/seedu/ddd/logic/commands/ListClientCommand.java
  src/main/java/seedu/ddd/logic/commands/ListContactCommand.java
  src/main/java/seedu/ddd/logic/commands/ListEventCommand.java
  src/main/java/seedu/ddd/logic/commands/ListVendorCommand.java
  src/main/java/seedu/ddd/logic/parser/ListClientCommandParser.java
  src/main/java/seedu/ddd/logic/parser/ListVendorCommandParser.java
  src/main/java/seedu/ddd/model/ModelManager.java
  src/main/java/seedu/ddd/model/contact/common/predicate/ClientPredicateBuilder.java
  src/main/java/seedu/ddd/model/contact/common/predicate/ClientTypePredicate.java
  src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
  src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
  src/main/java/seedu/ddd/model/contact/common/predicate/VendorTypePredicate.java
  src/test/java/seedu/ddd/logic/commands/ListClientCommandTest.java
  src/test/java/seedu/ddd/logic/commands/ListEventCommandTest.java
  src/test/java/seedu/ddd/logic/commands/ListVendorCommandTest.java
  src/test/java/seedu/ddd/model/ModelManagerTest.java
  src/test/java/seedu/ddd/model/contact/common/predicate/ClientPredicateBuilderTest.java
  src/test/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilderTest.java
  src/test/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilderTest.java
Labels: Bug

#174 Fix test fails
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/ddd/model/ModelManagerTest.java
  src/test/java/seedu/ddd/testutil/contact/TypicalContacts.java
Labels: alpha-bug

#184 Fix edit contact association with events
  src/main/java/seedu/ddd/logic/commands/EditContactCommand.java
  src/test/java/seedu/ddd/logic/commands/EditContactCommandTest.java
Labels: alpha-bug

#190 Update HelpWindow styles
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.css
  src/main/resources/view/Sidebar.css
Labels: enhancement

#195 Update Event toString
  src/main/java/seedu/ddd/model/contact/common/Contact.java
  src/main/java/seedu/ddd/model/event/common/Event.java
  src/test/java/seedu/ddd/model/contact/client/ClientTest.java
  src/test/java/seedu/ddd/model/contact/common/ContactTest.java
  src/test/java/seedu/ddd/model/contact/vendor/ServiceTest.java
  src/test/java/seedu/ddd/model/contact/vendor/VendorTest.java
  src/test/java/seedu/ddd/model/event/common/EventTest.java
Labels: enhancement

#197 Improve test coverage for AddCommand
  src/main/java/seedu/ddd/logic/LogicManager.java
  src/main/java/seedu/ddd/logic/Messages.java
  src/main/java/seedu/ddd/logic/commands/add/AddCommand.java
  src/main/java/seedu/ddd/logic/commands/add/AddContactCommand.java
  src/main/java/seedu/ddd/logic/commands/add/AddEventCommand.java
  src/main/java/seedu/ddd/logic/parser/add/AddClientCommandParser.java
  src/main/java/seedu/ddd/logic/parser/add/AddEventCommandParser.java
  src/main/java/seedu/ddd/logic/parser/add/AddVendorCommandParser.java
  src/main/java/seedu/ddd/logic/parser/add/AddressBookParser.java
  src/main/java/seedu/ddd/model/AddressBook.java
  src/main/java/seedu/ddd/model/Model.java
  src/main/java/seedu/ddd/model/ModelManager.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/ddd/logic/MessagesTest.java
  src/test/java/seedu/ddd/logic/commands/add/AddContactCommandIntegrationTest.java
  src/test/java/seedu/ddd/logic/commands/add/AddContactCommandTest.java
  src/test/java/seedu/ddd/logic/commands/add/AddEventCommandIntegrationTest.java
  src/test/java/seedu/ddd/logic/commands/add/AddEventCommandTest.java
  src/test/java/seedu/ddd/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/ddd/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/ddd/logic/parser/add/AddClientCommandParserTest.java
  src/test/java/seedu/ddd/logic/parser/add/AddEventCommandParserTest.java
  src/test/java/seedu/ddd/logic/parser/add/AddVendorCommandParserTest.java
  src/test/java/seedu/ddd/model/AddressBookTest.java
  src/test/java/seedu/ddd/model/ModelManagerTest.java
  src/test/java/seedu/ddd/model/event/common/UniqueEventListTest.java
  src/test/java/seedu/ddd/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/ddd/testutil/contact/ClientBuilder.java
  src/test/java/seedu/ddd/testutil/contact/ClientUtil.java
  src/test/java/seedu/ddd/testutil/contact/VendorUtil.java
  src/test/java/seedu/ddd/testutil/event/EventUtil.java
  src/test/java/seedu/ddd/testutil/event/TypicalEventFields.java
  src/test/java/seedu/ddd/testutil/event/TypicalEvents.java
Labels: enhancement

#222 Prevent client and vendor fields from collapsing
  src/main/resources/view/EventCard.fxml
Labels: alpha-bug

#224 Fix consecutive special charactes not being allowed in email
  src/main/java/seedu/ddd/model/contact/common/Address.java
  src/main/java/seedu/ddd/model/contact/common/Email.java
  src/main/java/seedu/ddd/model/contact/common/Phone.java
  src/test/java/seedu/ddd/model/contact/common/EmailTest.java
Labels: alpha-bug

#223 Simple fix on possible list of empty vendors
  src/main/java/seedu/ddd/logic/Messages.java
  src/main/java/seedu/ddd/logic/commands/DeleteCommand.java
  src/main/java/seedu/ddd/model/AddressBook.java
  src/test/java/seedu/ddd/logic/commands/DeleteCommandTest.java
Labels: alpha-bug

#218 Filter events by date
  docs/UserGuide.md
  src/main/java/seedu/ddd/MainApp.java
  src/main/java/seedu/ddd/logic/Messages.java
  src/main/java/seedu/ddd/logic/parser/ParserUtil.java
  src/main/java/seedu/ddd/logic/parser/list/ListClientCommandParser.java
  src/main/java/seedu/ddd/logic/parser/list/ListContactCommandParser.java
  src/main/java/seedu/ddd/logic/parser/list/ListEventCommandParser.java
  src/main/java/seedu/ddd/logic/parser/list/ListVendorCommandParser.java
  src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
  src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
  src/main/java/seedu/ddd/model/event/common/predicate/EventDatePredicate.java
  src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
  src/test/java/seedu/ddd/model/event/common/predicate/EventDatePredicateTest.java
  src/test/java/seedu/ddd/model/event/common/predicate/EventIdPredicateTest.java
  src/test/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilderTest.java
Labels: priority.Medium, feature

#228 Add check for event related problem
  docs/UserGuide.md
  src/main/java/seedu/ddd/storage/JsonSerializableAddressBook.java
Labels: severity.High, alpha-bug

#226 Remove whitespace in DG
  docs/DeveloperGuide.md
Labels: priority.Low, documentation

#220 Add introduction section in UG
  docs/UserGuide.md
  docs/images/budgetTagDemo.png
  docs/images/eventDemo.png
  docs/images/github-icon.png
  docs/images/helpMessage.png
  docs/images/request_access.png
Labels: documentation

#230 Fix HTML table styles
  docs/UserGuide.md
Labels: documentation

#234 Update UML diagrams for model
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#297 Fix typing id/one will hang the product.
  docs/diagrams/ParserClasses.puml
  src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
  src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
  src/test/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilderTest.java
  src/test/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilderTest.java
Labels: priority.Medium

#298 Update User Stories and fix typos in UG.
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#301 Add Use case
  docs/DeveloperGuide.md
Labels: documentation

#306 Fixed bug for email and phone where input is invalid
  src/main/java/seedu/ddd/model/common/Name.java
  src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
  src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
  src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
  src/test/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilderTest.java
  src/test/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilderTest.java
Labels: bug

#309 Fix error message for id and update ug
  docs/UserGuide.md
  src/main/java/seedu/ddd/logic/parser/ParserUtil.java
Labels: bug, documentation

#310 Add known issues
  docs/UserGuide.md
Labels: documentation

#312 Change the check to use previously used method
  src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
  src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
  src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
Labels: severity.VeryLow
